use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'AHFMHistoryVCManager_Example' do
  pod 'AHFMHistoryVCManager', :path => '../'

  target 'AHFMHistoryVCManager_Tests' do
    inherit! :search_paths

    
  end
end
